# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testSQl',
            fields=[
                ('ImgH', models.IntegerField()),
                ('ImgW', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
