# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DinggeServer', '0002_auto_20160810_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='markData',
            fields=[
                ('mainStX', models.IntegerField()),
                ('mainStY', models.IntegerField()),
                ('mainEdX', models.IntegerField()),
                ('mainEdY', models.IntegerField()),
                ('Score', models.IntegerField()),
                ('markId', models.AutoField(primary_key=True, serialize=False)),
                ('picId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DinggeServer.PicInfo')),
            ],
        ),
    ]
